### PR TITLE
Convert project to python3

### PR DESCRIPTION
**Pull request by guysoft**
I have no way to test this, if someone wants to try and report

### CODE REVIEW

**Comment by vu3wzv** [comment]
i modified import section as follows

```
import os.path
import modules.SvxlinkwrapperModule
from subprocess import PIPE, Popen
from straight.plugin import load

from configparser import ConfigParser
```

now i received the following errors

pi@vu2poc:~/SvxLinkWrapper $ python src/SvxLinkWrapper.py
b'SvxLink v1.8.99.8@24.02-45-g6743b5b7 Copyright (C) 2003-2024 Tobias Blomberg / SM0SVX'
Traceback (most recent call last):
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 115, in <module>
    a = SvxLinkWrapper()
        ^^^^^^^^^^^^^^^^
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 66, in __init__
    self.handleStdout(line)
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 88, in handleStdout
    plugin.handleStdout(line)
  File "/home/pi/SvxLinkWrapper/src/modules/EcholinkAutoConnectModule.py", line 41, in handleStdout
    if line.startswith("--- EchoLink directory server message: ---"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by guysoft** [comment]
1. Can you post exactly what you changed? It looks like its working for me on python 3.12
2. Pull and use the latest python3 branch I updated your import changes

**Comment by vu3wzv** [comment]
pi@vu2poc:~/SvxLinkWrapper $ sudo python3.13 src/SvxLinkWrapper.py
SvxLink v1.8.99.8@24.02-45-g6743b5b7 Copyright (C) 2003-2024 Tobias Blomberg / SM0SVX

SvxLink comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
welcome to redistribute it in accordance with the terms and conditions in the

GNU GPL (General Public License) version 2 or later.

Using configuration file: /etc/svxlink/svxlink.conf
--- Using sample rate 48000Hz

Starting logic: SimplexLogic
        Found plugin: /usr/lib/aarch64-linux-gnu/svxlink/SimplexLogic.so
SimplexLogic: Loading RX "Rx1"
Rx1: Delay line (for DTMF muting etc) set to 40 ms
SimplexLogic: Loading TX "Tx1"
SimplexLogic: Loading module "ModuleEchoLink"
        Found /usr/lib/aarch64-linux-gnu/svxlink/ModuleEchoLink.so
SimplexLogic: Event handler script successfully loaded.
        Module EchoLink v1.6.0@24.02-45-g6743b5b7 starting...
Connected to APRS server 195.190.142.207 on port 14580
EchoLink directory status changed to ON
--- EchoLink directory server message: ---
EchoLink Server v2.6.150

ECHO4: Frankfurt, Germany

SimplexLogic: Activating module EchoLink...
ModuleEchoLink: Trying autoconnect to 9999
Connecting to *ECHOTEST* (9999)
EchoLink: Using GSM codec only
Tx1: Turning the transmitter ON
*ECHOTEST*: EchoLink QSO state changed to CONNECTING
Tx1: Turning the transmitter OFF
*ECHOTEST*: EchoLink QSO state changed to DISCONNECTED
SVXLinkWrapper:*ECHOTEST*



**Traceback (most recent call last):
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 118, in <module>
    a = SvxLinkWrapper()
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 69, in __init__
    self.handleStdout(line)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/pi/SvxLinkWrapper/src/SvxLinkWrapper.py", line 91, in handleStdout
    plugin.handleStdout(line)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/pi/SvxLinkWrapper/src/modules/EcholinkLoggerModule.py", line 81, in handleStdout
    self.database.endQSO(station,self.csName,self.csIP)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SvxLinkWrapper/src/modules/EcholinkLoggerModule.py", line 56, in endQSO
    self.insertQSO(ips,names,cs,"exit")
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/SvxLinkWrapper/src/modules/EcholinkLoggerModule.py", line 39, in insertQSO
    variables = (cs,None,ip,buffer(name),state,str(time.time()))
                            ^^^^^^
NameError: name 'buffer' is not defined**

here attached  SvxLinkwrapper.py
[SvxLinkWrapper.py.txt](https://github.com/user-attachments/files/17475922/SvxLinkWrapper.py.txt)

**Comment by guysoft** [comment]
Updated, removed buffer(), try again

**Comment by guysoft** [comment]
@vu3wzv Is SvxLinkWrapper working with latest version of SvxLink?
And can these changes get merged? or is anything else broken?

**Comment by vu3wzv** [comment]
in SvxLink 24.x everything is working fine. and also checked in python3.11 , 3.12, 3.13. 
Thanks for your excellent work.

**Pull request merged**
